In [57]:
# 1 - DATA MANIPULATION
import pandas as pd
import numpy as np

# 2 - DATA VISUALISATION
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# 3 - STATISTICS
from statsmodels.graphics.gofplots import qqplot
from scipy import stats

# 4 - MACHINE LEARNING

from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.ensemble import RandomForestRegressor
import itertools
from xgboost import XGBRegressor

## 4.1 - Preprocessing

### 4.1.1 - Scalers
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor

### 4.1.2 - Encoders
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

### 4.1.3 - Crossvalidation, Training, Model
from sklearn.model_selection import cross_validate, GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression, ElasticNet

### 4.1.4 - Evaluation
from sklearn.metrics import confusion_matrix, r2_score, accuracy_score
from sklearn.metrics  import ConfusionMatrixDisplay

In [2]:
df_males = pd.read_csv('../data_csv/data_model_males.csv')
df_females = pd.read_csv('../data_csv/data_model_females.csv')

In [3]:
df_males.head()

,Name,Exercise,Metric,Height,Weight,0,1,2,3,4,...,90,91,92,93,94,95,96,97,98,99
0,Robert,Chest,Chest_Weight,185,80,35.0,35.0,36.0,36.0,36.0,...,78.0,79.0,80.0,80.0,80.0,81.0,81.0,81.0,81.0,82.0
1,Robert,Chest,Chest_Repetitions,185,80,8.0,10.0,8.0,10.0,12.0,...,8.0,8.0,8.0,10.0,12.0,8.0,10.0,12.0,14.0,8.0
2,Robert,Shoulders,Shoulders_Weight,185,80,7.0,7.0,7.0,7.0,7.0,...,10.5,10.5,10.5,10.5,10.5,10.5,10.5,10.5,10.5,10.5
3,Robert,Shoulders,Shoulders_Repetitions,185,80,8.0,8.0,8.0,8.0,8.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
4,Robert,Legs,Legs_Weight,185,80,60.0,60.0,60.0,62.0,62.0,...,116.0,117.0,117.0,117.0,118.0,118.0,119.0,119.0,119.0,119.0

In [4]:
df_females.head()

,Name,Exercise,Metric,Height,Weight,0,1,2,3,4,...,90,91,92,93,94,95,96,97,98,99
0,Julia,Chest,Chest_Weight,160,52,21.0,21.5,22.0,22.5,22.5,...,47.5,48.5,48.5,48.5,49.0,49.5,49.5,49.5,50.0,50.5
1,Julia,Chest,Chest_Repetitions,160,52,8.0,8.0,8.0,8.0,10.0,...,8.0,8.0,10.0,12.0,8.0,8.0,10.0,12.0,8.0,8.0
2,Julia,Shoulders,Shoulders_Weight,160,52,4.0,4.0,4.0,4.0,4.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
3,Julia,Shoulders,Shoulders_Repetitions,160,52,8.0,9.0,10.0,11.0,12.0,...,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,15.0,15.0
4,Julia,Legs,Legs_Weight,160,52,30.5,30.5,31.0,31.5,31.5,...,66.5,67.0,68.0,68.5,69.0,69.0,69.5,69.5,70.0,70.5

In [5]:
df_males.describe()

,Height,Weight,0,1,2,3,4,5,6,7,...,90,91,92,93,94,95,96,97,98,99
count,32.000000,32.000000,32.00000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,...,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,176.250000,71.750000,18.37500,19.031250,19.250000,19.750000,20.187500,20.390625,20.421875,20.953125,...,38.671875,38.953125,38.953125,39.093750,39.562500,39.921875,40.031250,39.968750,40.359375,40.500000
std,6.753733,11.878416,17.12525,17.001868,17.305602,17.454087,17.620438,17.946486,18.408058,18.242258,...,40.146026,40.430418,40.686718,41.028007,41.046541,41.199184,41.528447,41.851107,42.007533,42.227113
min,168.000000,55.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
25%,171.000000,64.000000,8.00000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.750000,...,9.000000,8.750000,9.000000,8.750000,9.750000,9.000000,9.000000,9.875000,9.875000,9.875000
50%,176.000000,73.500000,8.00000,10.000000,10.000000,11.000000,12.000000,12.500000,11.000000,11.000000,...,13.000000,13.000000,12.250000,11.500000,12.250000,13.250000,12.250000,12.250000,13.250000,13.250000
75%,181.250000,81.250000,20.25000,21.000000,21.250000,21.250000,22.000000,22.000000,22.250000,22.750000,...,68.750000,69.750000,69.750000,70.500000,70.750000,71.000000,71.000000,72.000000,72.250000,72.500000
max,185.000000,85.000000,62.00000,63.000000,64.000000,65.000000,65.000000,66.000000,68.000000,68.000000,...,134.000000,135.000000,135.000000,136.000000,137.000000,137.000000,137.000000,139.000000,139.000000,140.000000

In [6]:
df_m = df_males.drop(columns = ['Name'])
df_f = df_females.drop(columns = ['Name'])

In [7]:
m_chest = df_m[df_m['Exercise'] == 'Chest']
f_chest = df_f[df_f['Exercise'] == 'Chest']
m_shoulders = df_m[df_m['Exercise'] == 'Shoulders']
f_shoulders = df_f[df_f['Exercise'] == 'Shoulders']
m_legs = df_m[df_m['Exercise'] == 'Legs']
f_legs = df_f[df_f['Exercise'] == 'Legs']
m_back = df_m[df_m['Exercise'] == 'Back']
f_back = df_f[df_f['Exercise'] == 'Back']

In [8]:
m_chest = m_chest.drop(columns=['Exercise'])
f_chest = f_chest.drop(columns=['Exercise'])
m_shoulders = m_shoulders.drop(columns=['Exercise'])
f_shoulders = f_shoulders.drop(columns=['Exercise'])
m_legs = m_legs.drop(columns=['Exercise'])
f_legs = f_legs.drop(columns=['Exercise'])
m_back = m_back.drop(columns=['Exercise'])
f_back = f_back.drop(columns=['Exercise'])

In [9]:
dfs = [m_chest, f_chest, m_shoulders, f_shoulders, m_legs, f_legs, m_back, f_back]
for df in dfs:
    for row  in df['Metric']:
        words_metric = row.split('_')
    df['Metric'] = df['Metric'].map({f'{words_metric[0]}_Weight': 0, f'{words_metric[0]}_Repetitions': 1})

In [18]:
mms = MinMaxScaler()

In [19]:
mms.fit(m_chest)

/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

MinMaxScaler()

In [20]:
m_chest_pp = mms.transform(m_chest)

/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [24]:
m_chest_pp = pd.DataFrame(m_chest_pp, columns = m_chest.columns)

In [25]:
m_chest_pp

,Metric,Height,Weight,0,1,2,3,4,5,6,...,90,91,92,93,94,95,96,97,98,99
0,0.0,1.000000,0.833333,0.627907,0.613636,0.622222,0.608696,0.608696,0.617021,0.604167,...,0.729167,0.739583,0.750000,0.734694,0.734694,0.737374,0.722772,0.717172,0.715686,0.725490
1,1.0,1.000000,0.833333,0.000000,0.045455,0.000000,0.043478,0.086957,0.000000,0.041667,...,0.000000,0.000000,0.000000,0.020408,0.040816,0.000000,0.019802,0.020202,0.058824,0.000000
2,0.0,0.000000,0.000000,0.302326,0.295455,0.311111,0.304348,0.304348,0.297872,0.312500,...,0.552083,0.572917,0.572917,0.571429,0.581633,0.575758,0.564356,0.555556,0.558824,0.568627
3,1.0,0.000000,0.000000,0.000000,0.045455,0.000000,0.043478,0.086957,0.127660,0.000000,...,0.062500,0.000000,0.020833,0.000000,0.000000,0.020202,0.039604,0.040404,0.078431,0.000000
4,0.0,0.705882,1.000000,1.000000,0.977273,0.977778,0.956522,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
5,1.0,0.705882,1.000000,0.000000,0.045455,0.000000,0.043478,0.000000,0.000000,0.000000,...,0.000000,0.020833,0.041667,0.000000,0.020408,0.000000,0.000000,0.000000,0.000000,0.019608
6,0.0,0.235294,0.400000,1.000000,1.000000,1.000000,1.000000,1.000000,0.978723,0.979167,...,0.864583,0.875000,0.885417,0.867347,0.867347,0.858586,0.851485,0.848485,0.843137,0.843137
7,1.0,0.235294,0.400000,0.000000,0.000000,0.000000,0.000000,0.043478,0.085106,0.000000,...,0.020833,0.000000,0.000000,0.020408,0.040816,0.060606,0.000000,0.000000,0.039216,0.058824

In [26]:
m_chest

,Metric,Height,Weight,0,1,2,3,4,5,6,...,90,91,92,93,94,95,96,97,98,99
0,0,185,80,35.0,35.0,36.0,36.0,36.0,37.0,37.0,...,78.0,79.0,80.0,80.0,80.0,81.0,81.0,81.0,81.0,82.0
1,1,185,80,8.0,10.0,8.0,10.0,12.0,8.0,10.0,...,8.0,8.0,8.0,10.0,12.0,8.0,10.0,12.0,14.0,8.0
8,0,168,55,21.0,21.0,22.0,22.0,22.0,22.0,23.0,...,61.0,63.0,63.0,64.0,65.0,65.0,65.0,65.0,65.0,66.0
9,1,168,55,8.0,10.0,8.0,10.0,12.0,14.0,8.0,...,14.0,8.0,10.0,8.0,8.0,10.0,12.0,14.0,16.0,8.0
16,0,180,85,51.0,51.0,52.0,52.0,54.0,55.0,56.0,...,104.0,104.0,104.0,106.0,106.0,107.0,109.0,109.0,110.0,110.0
17,1,180,85,8.0,10.0,8.0,10.0,8.0,8.0,8.0,...,8.0,10.0,12.0,8.0,10.0,8.0,8.0,10.0,8.0,10.0
24,0,172,67,51.0,52.0,53.0,54.0,54.0,54.0,55.0,...,91.0,92.0,93.0,93.0,93.0,93.0,94.0,94.0,94.0,94.0
25,1,172,67,8.0,8.0,8.0,8.0,10.0,12.0,8.0,...,10.0,8.0,8.0,10.0,12.0,14.0,8.0,10.0,12.0,14.0

In [37]:
y = pd.DataFrame({100: [82.0, 10.0, 66.0, 10.0, 110.0, 12.0, 95.0, 8.0]})

In [38]:
x_train, x_test, y_train, y_test = train_test_split(m_chest_pp, y, test_size=0.4)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test)

In [49]:
lr = RandomForestRegressor()
lr.fit(x_train, y_train)

/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/tmp/ipykernel_2517/3122192897.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr.fit(x_train, y_train)

RandomForestRegressor()

In [50]:
yhat = lr.predict(x_test)

/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/home/clement/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [51]:
y_test

    100
2  66.0
1  10.0
7   8.0

In [52]:
pd.DataFrame(yhat)

       0
0  68.58
1  15.29
2  16.34